// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc2538.AerialAssistTest;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveSystemforPort;
    public static SpeedController driveSystemforAft;
    public static SpeedController driveSystemstarboardFor;
    public static SpeedController driveSystemstarboardAft;
    public static RobotDrive driveSystemmecanumDrive;
    public static SpeedController driveSystemSpeedController1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveSystemforPort = new Talon(1, 1);
	LiveWindow.addActuator("driveSystem", "forPort", (Talon) driveSystemforPort);
        
        driveSystemforAft = new Talon(1, 2);
	LiveWindow.addActuator("driveSystem", "forAft", (Talon) driveSystemforAft);
        
        driveSystemstarboardFor = new Talon(1, 3);
	LiveWindow.addActuator("driveSystem", "starboardFor", (Talon) driveSystemstarboardFor);
        
        driveSystemstarboardAft = new Talon(1, 4);
	LiveWindow.addActuator("driveSystem", "starboardAft", (Talon) driveSystemstarboardAft);
        
        driveSystemmecanumDrive = new RobotDrive(driveSystemforPort, driveSystemforAft,
              driveSystemstarboardFor, driveSystemstarboardAft);
	
        driveSystemmecanumDrive.setSafetyEnabled(true);
        driveSystemmecanumDrive.setExpiration(0.1);
        driveSystemmecanumDrive.setSensitivity(0.5);
        driveSystemmecanumDrive.setMaxOutput(1.0);
        driveSystemSpeedController1 = new Victor(1, 5);
	LiveWindow.addActuator("driveSystem", "Speed Controller 1", (Victor) driveSystemSpeedController1);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
